#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Shop\Electronic\ElectronicCommand;

$application = new Application();

// ... register commands
$application->add(new ElectronicCommand());

$application->run();